services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-network

  kafka-server-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  my-python-producer:
      image: mpradeep954/fetch-de-data-gen
      depends_on:
        - kafka-server-1
      restart: on-failure:10
      ports:
        - 9093:9093
      environment:
        BOOTSTRAP_SERVERS: kafka-server-1:9092
        KAFKA_TOPIC: user-login
      networks:
      - kafka-network

  user-processor:
      image: pal666/user-processor:v2.2
      depends_on:
        - my-python-producer
      environment:
        BOOTSTRAP_SERVER: kafka-server-1:9092
        CONSUMER_TOPIC: user-login
        PRODUCER_TOPIC: login-user-processed
      networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
    